version: 0.0
os: linux
files:
  - source:  /
    destination: /home/app/foocebak
    overwrite: yes

permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      runas: ubuntu