version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/app/foocebak/deploy
    overwrite: yes

permissions:
  - object: /home/ubuntu
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 4755

hooks:
  AfterInstall:
    - location: deploy.sh
      runas: ubuntu