version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/foocebak
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 4755

hooks:
  AfterInstall:
    - location: deploy/deploy.sh
      runas: ubuntu