name: CI-CD

on:
    push:
      branches: [ master ]

env:
  S3_BUCKET_NAME: bucketforautodistribute
  RESOURCE_PATH: ./src/main/resources/application.yml
  CODE_DEPLOY_APPLICATION_NAME: bucketforautodistribute
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: foocebak-server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          

      - name: Set yaml file
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ env.RESOURCE_PATH }}
        env:
          override.value: 'from deploy.yaml'
          
          spring.datasource.url: ${{ secrets.AWS_URL}}       
          spring.datasource.username: ${{ secrets.AWS_RDS_USERNAME }} 
          spring.datasource.password: ${{ secrets.AWS_RDS_PASSWORD }} 
          cloud.aws.credentials.access-key: ${{ secrets.AWS_ACCESS_KEY_ID_ENV }}
          cloud.aws.credentials.secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ENV }}
          cloud.aws.region.static: ${{ secrets.AWS_REGION }}
          cloud.aws.s3.bucket.url: ${{ secrets.S3_BUCKET_URL}}
          cloud.aws.s3.bucket: springblog
          spring.servlet.multipart.max-file-size: 20MB
          spring.servlet.multipart.max-request-size: 20MB
          spring.jpa.hibernate.ddl-auto: update
          
          server.servlet.encoding.charset: utf-8
          server.servlet.encoding.enabled: true
          server.servlet.encoding.force: true
          spring.jackson.serialization.FAIL_ON_EMPTY_BEANS: false
          logging.level.com.amazonaws.util.EC2MetadataUtils: error
          spring.mvc.pathmatch.matching-strategy: ant_path_matcher

          
          
          spring.security.oauth2.client.registration.kakao.client-id: ${{ secrets.KAKAO_CLIENT_ID}}
          spring.security.oauth2.client.registration.kakao.client-secret : ${{ secrets.KAKAO_CLIENT_SCERET}}
          spring.security.oauth2.client.registration.kakao.scope: profile_nickname, profile_image, account_email
          spring.security.oauth2.client.registration.kakao.redirect-uri : ${{ secrets.KAKAO_REDIRECT}}
          
          jwt.secret: ${{ secrets.JWT_SECRET}} 
          
          
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

        # [2]
      - name: Build with Gradle
        run: ./gradlew build -x test
        shell: bash

        # [3]
      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

        # [4]
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: ${{ secrets.AWS_REGION }} 

        # [5]
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://bucketforautodistribute/$GITHUB_SHA.zip

        # [6]
      - name: Code Deploy
        run: | 
          aws deploy create-deployment \
          --application-name foocebak \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name foocebak-server \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$GITHUB_SHA.zip
